{% set name = "Flask-Jsonpify" %}
{% set version = "1.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "8ac4c732aa5b11d9f6c2de58065d3b669f139518ca8f529bce943817e2fedbfb" %}
{% set build = 1001 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: {{ build }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - flask

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - flask_jsonpify

about:
  home: https://github.com/CoryDolphin/flask-jsonpify
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: MIT
  license_family: MIT
  summary: 'A Flask extension adding a decorator for JSONP support'
  dev_url: https://github.com/CoryDolphin/flask-jsonpify


extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
