appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ynYMDGaWoLFXVnLkqIv+v0NEHxgNNYSXYdlU9kq73tl6rnIDaj+GTcagflwg4gkkDE/hGqryL6FaENhfu4p66yAEOIVqe4vCMBCiMGJ7vm2lXVZQa3kLV2nGpDm/qZfq/e+Yq6xnuKqLvElBviBS2uM0EYRylNsh4jgQqoqLkp77qor+750uVitjQewyVvjJFg31Rnou2dOv5BQgA+IdveKN8WPpLCkTXUmZUYk0CG7nCDj2o4EjdzuWahVOGZK2/iHmaAzvEf7FvYuaHjgoPEt7Qg4YTWZjwBo1u1zA3JA1AowXbmU+Ju0LxENNRfdzRjd/i/i/T7fZWWhv97a2oG4P2e3czXBS/+cpwOOC9kym2fNLUJVEUuxRC+EnEFm1buxklTLCa1P/ispJ8Le3ZWNckl88DHSI0/vSRnTRBkgQ3efO1XwYKiL48Qqs7q850xUNRqNujCaYhcdfgoCXwnTokfsb6XH2mc595e2CHjVK9XP840VHw4YxWAL3IiAV+pAPymL1Evcfrf9JUQFtn9gheoq63wpLmFxbZoQ71I8u8N/RzPQclsOFiIyHJ+DQaHuQ2mc4M+7P+rWNubRbjuTePtC1SS6bx3zG4UnoBSaQBl4VgxEjXT1kT9VFF+dxJ/sLtEcItRv/rSvHsPV10NJtaHtl+EkydF7/vFOouRI=}
