travis:
  secure:
    BINSTAR_TOKEN: hImdHE7/MULrD1EVWaRLud8SkMwA8ds/T+1oqOG4j1/uRFWP2D6jpH3DGzToawNrRqefRYD76qRrETlslo2Nrw8DvsFrHRFweuo8wvB9EfstiCbx4Lmej23Sa7qXHM0bXR7YbNQRGwUQTx+/SX66VCQcvU9JJDR43GLtOlBAA7xEkJpQN1bT3cosppVQymp3msZKdT1RYHdx4/z3CUddzL3ptYqK7Zf9xUQirG2zQ6LXpho1PJRLC/Ve0OWZjgRu2HBCH+R7CMLVIMrl6n9AtRdJf7wcB4sAl2A75R2AbMYVcZsegqh+BDSjSMg4Kg3Pz8ZGtpNoo8L9hpPvG6gY1w9glqHxeMTM7L0ZvkdZAmQvGmkhFbPn77QQW16uQ0/0UC5hidEYeW2bG2YzUxwf8G9iKJkJ4QUgu5jID2aVEqkLkqOsUPI4iCJnfurc9Bl+1OtEI9Et/qUpFmj2SjEZ6HVYnhSPLV2lNXKHr3p+K5w4M7RwETq56abe0AI0csTdSW3wYWvpYpejlkCWGGJLYzPJBo5XlRU5dmF3koak/D25sjdRAsy5nZ5IJvKrPfXXUdIUAIVOQLPbJZ3dulS6qtBo0ddT9CaHHD6kYQ9TJA4RDJjE8nsHWHs9E7eJHoEhloleMqSpHdpn4jrp8zGofiAW1WfIB+i5w+t6XtCQmSA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
